spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/livet
    username: livet
    password: livet
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      pool-name: HikariPool-1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

