server:
  port: 8080

logging:
  level:
    root: INFO
    br.com.livet: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

spring:
  managentent:
    endpoints:
      enabled-by-default: true
    endpoint:
      health:
        enabled: true
  flyway:
    locations: classpath:db/migration
    schemas: public
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      pool-name: HikariPool-1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

firebase:
  authenticationKey:
  authenticationUrl: https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=${firebase.authenticationKey}
  refreshTokenUrl: https://securetoken.googleapis.com/v1/token?key=${firebase.authenticationKey}
